name: normal_build

on:
  push:
  pull_request:

jobs:
  gen_artifacts:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install -U --user -r misc/requirements.txt

    - name: Build firmware (release version)
      run: |
        export PATH=$PATH:$HOME/.local/bin
        platformio run -j 16 -e release
      env:
        FIRMWARE_PUBLIC_KEY: ${{ secrets.FIRMWARE_PUBLIC_KEY }}
        FIRMWARE_SIGNING_PKEY: ${{ secrets.FIRMWARE_SIGNING_PKEY }}

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: |
          .pio/build/release/firmware_*.sig
